# <font color='blue'>Lab Final - CKCS 149 Python Programming</font>

We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle. I have downloaded the file for you. 

### <font color='red'> Answer the following questions and submit a PDF file on the D2L. </font>

Follow the instructions and have a look at the output to answer the following questions.

**Import pandas as pd.**

In [1]:
import pandas as pd
import numpy as np

**Read Salaries.csv as a dataframe called sal.**

In [2]:
sal = pd.read_csv('Salaries.csv')

**1- Check the head of the DataFrame.**

In [5]:
import pandas as pd
import numpy as np
# I had to do the import again because Jupyter said 'pd' was not defined

sal = pd.read_csv('Salaries.csv')
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

**2- Use the .info() method to find out about datatypes of featues and basic details about the dataset**

In [6]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

**3- Use the .describe() method to find out summaries of numeric columns**

In [7]:
sal.describe()

,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Status
count,148654.000000,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000,0.0,0.0
mean,74327.500000,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643,NaN,NaN
std,42912.857795,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538,NaN,NaN
min,1.000000,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000,NaN,NaN
25%,37164.250000,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000,NaN,NaN
50%,74327.500000,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000,NaN,NaN
75%,111490.750000,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000,NaN,NaN
max,148654.000000,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000,NaN,NaN

**4- What is the average TotalPay?**

In [13]:
avg_total_pay = sal['TotalPay'].mean()
print(avg_total_pay)

# I'm using a print statement because without it, the code cell will display the datatype beside the output - which makes it look cluttered.

74768.32197169267

**5- What is the highest amount of BasePay in the dataset ?**

In [14]:
max_base_pay = sal['BasePay'].max()
print(max_base_pay)

319275.01

**6- How many Employees do not get Benefits? (How many NaN records do we have in the Benefits column?)**

In [12]:
no_benefits_count = sal['Benefits'].isnull().sum()
print(no_benefits_count)

36163

**7- How many Employees received OvertimePay? (Count the greater then 0 cells in the OvertimePay Column)**

In [15]:
overtime_count = (sal['OvertimePay'] > 0).sum()
print(overtime_count)

71328

**8- What are the job title of employees with names Claudia M Sanchez?**

In [18]:
job_title = sal[sal['EmployeeName'] == "Claudia M Sanchez"]['JobTitle']
print(job_title)

90714     Senior Eligibility Worker
128232    HSA Sr Eligibility Worker
Name: JobTitle, dtype: object

**9- How much does JOSEPH DRISCOLL make (including benefits)?**

In [19]:
total_pay_benefits = sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']
print(total_pay_benefits)

24    270324.91
Name: TotalPayBenefits, dtype: float64

**10- What is the name of highest paid person (including benefits)?**

In [24]:
highest_paid_person = sal.loc[sal['TotalPayBenefits'].idxmax()]['EmployeeName']
print(highest_paid_person)

# I used .idxmax() to get the index of the highest value in the TotalPayBenefits column. 
# I used .loc to retrieve the row corresponding to that index
# From that row I pulled the 'EmployeeName'

NATHANIEL FORD

**11- What was the average (mean) TotalPayBenefits for all employees per year? (2011-2014) ?**

In [25]:
yearly_average = sal.groupby('Year')['TotalPayBenefits'].mean()
print(yearly_average)

Year
2011     71744.103871
2012    100553.229232
2013    101440.519714
2014    100250.918884
Name: TotalPayBenefits, dtype: float64

**12- How many unique EmployeeName are there in the dataset?**

In [26]:
unique_names_count = len(sal['EmployeeName'].unique())
print(unique_names_count)

110811

**13- What are the top 5 most common jobs?**

In [31]:
most_common_jobs = sal['JobTitle'].value_counts().head()
print(most_common_jobs)

# value_counts() to count the frequency of unique values in 'JobTitle' column
# head() to display the top 5 unique values

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

**14- How many Job Titles were represented by only three persons in 2011? (e.g. Job Titles with only three occurences in 2011?)**

In [34]:
sal_counts_2011 = sal[sal['Year'] == 2011]['JobTitle'].value_counts()
three_person_count = sum(sal_counts_2011 == 3)
print(three_person_count)

62

**15- How many people have the word Police in their job title?**

In [41]:
police_count = filter(lambda x: 'Police' in x, sal['JobTitle'])
print(len(list(police_count)))

# lambda acts as a for loop iterating on the JobTitle column and filtering for when 'Police' is in x
# in order to use len() on police_count, must make it a list(), now we can count the number of people with 'Police' in their job title

5689

**16- Print JobTitle of all employees whose name is 'Kevin Lee'**

In [44]:
kevin_lee_jobs = sal[sal['EmployeeName'] == 'Kevin Lee']['JobTitle']
print(kevin_lee_jobs)
print('\n')
print(kevin_lee_jobs.unique())

# I wasn't sure if you wanted every single instance of a jobtitle for someone named kevin lee or just the uniques, so I printed both.

39715                   Police Officer 3
40570                   Police Officer 3
42510     Electrical Transit System Mech
49270             Deputy Court Clerk III
49439             Deputy Court Clerk III
50123                  Personnel Analyst
52233     Senior Parking Control Officer
53931                   Transit Operator
55119                 IS Administrator 2
112385                        Sergeant 3
123141    IT Operations Support Admin IV
124165                 Personnel Analyst
124658                  Transit Operator
Name: JobTitle, dtype: object


['Police Officer 3' 'Electrical Transit System Mech'
 'Deputy Court Clerk III' 'Personnel Analyst'
 'Senior Parking Control Officer' 'Transit Operator' 'IS Administrator 2'
 'Sergeant 3' 'IT Operations Support Admin IV']

**17- Display records of the employees whose 'JobTitle' is 'Court Administrator'**

In [49]:
court_admin_records = sal.loc[sal['JobTitle'] == 'Court Administrator']
print(court_admin_records)

          Id      EmployeeName             JobTitle    BasePay  OvertimePay  \
39460  39461     Wayne Parinas  Court Administrator  133755.00          0.0
50068  50069   Claire Williams  Court Administrator   81589.86          0.0
75693  75694   Wayne D Parinas  Court Administrator  144061.50          0.0
83253  83254  Claire  Williams  Court Administrator   92616.88          0.0

       OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
39460      0.00  52738.53  133755.00         186493.53  2012    NaN
50068      0.00  37269.79   81589.86         118859.65  2012    NaN
75693   7128.63  50035.92  151190.13         201226.05  2013    NaN
83253   5715.75  39230.84   98332.63         137563.47  2013    NaN

              Agency  Status
39460  San Francisco     NaN
50068  San Francisco     NaN
75693  San Francisco     NaN
83253  San Francisco     NaN

**18- Is there a correlation between length of the Job Title string and Salary?**

In [50]:
sal['title_len'] = sal['JobTitle'].apply(len)
correlation_matrix = np.corrcoef(sal['title_len'], sal['TotalPayBenefits'])
correlation_value = correlation_matrix[0, 1]
print(correlation_value)

-0.03687844593260706